# Reusable workflow for Azure Board Reference validation
# This workflow can be called by other repositories to enforce Azure Board work item references in PRs
name: Azure Board Reference Check

on:
  workflow_call:
    inputs:
      skip-drafts:
        description: "Skip validation for draft PRs"
        required: false
        type: boolean
        default: true

jobs:
  azure-board-check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    outputs:
      ab-numbers: ${{ steps.check.outputs.ab-numbers }}
    steps:
      - name: Check for Azure Board Reference
        id: check
        uses: jacobwood091/azure-board-reference-check@main
        with:
          skip-drafts: ${{ inputs.skip-drafts || true }}
